version: '3.8'

services:
  saucedemo-tests:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: saucedemo-automation
    volumes:
      - ./build/allure-results:/app/build/allure-results
      - ./build/reports:/app/build/reports
    environment:
      - BROWSER=chrome
      - HEADLESS=true
      - BASE_URL=https://www.saucedemo.com
    command:
      - ./gradlew test

  allure-server:
    image: frankescobar/allure-docker-service
    container_name: allure-server
    ports:
      - "5050:5050"
    volumes:
      - ./build/allure-results:/app/allure-results
    environment:
      - CHECK_RESULTS_EVERY_SECONDS=3
      - KEEP_HISTORY=TRUE